name: Deploy to VPS (Bare-metal)

on:
  push:
    branches: [ "main" ]   # ganti kalau branch rilis beda
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-vps
      cancel-in-progress: false

    steps:
      - name: SSH to VPS and run deploy script
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            bash /usr/local/bin/deploy_backend_main.sh
